<?=$this->render('bootstrap/header',$data);?>
<?=$this->render('bootstrap/menu',$data);?>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alunos">
                    <div class="well">
                        <h1><?=$data->titulo?></h1>
                        <p>Wellington Leonardo</p>
                        <?=$data->content?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?=$this->render('bootstrap/footer',$data);?>

